server:
  port: 5004
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

user:
  admin:
    name: hello
    role: admin

#数据库设置
spring:
  data:
    mongodb:
      host: 119.23.39.30
      port: 5001
      database: trade1

logging:
        file:
          max-size: 10MB


